# Which type of trade flow analysis to run
# Trade flow type: 'imports', 'exports', or 'domestic'
TRADEFLOW: exports
YEAR: 2019
COUNTRY: US
FOLDERS:
  base: csv
  imports: csv/US/imports
  exports: csv/US/exports
  domestic: csv/US/domestic
FILES:
  factors: factor.csv
  industries: industry.csv
  industry_tradeflow: industry_tradeflow.csv
  trade_factor: trade_factor_lg.csv
  trade_impacts: trade_impact.csv
  trade_employment: trade_employment.csv
  trade_resources: trade_resource.csv
  trade_materials: trade_material.csv
PROCESSING:
  sample_size: 1000 # Number of trade flows to process for performance
  min_impact_threshold: 0.001 # Minimum impact value to include
